package templates;


import java.awt.Color;
import java.awt.GradientPaint;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.RenderingHints;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
/**
 *
 * @author Salles
 */
public class gradientBGAlpha extends javax.swing.JPanel {
    private float alpha = 0.00f;
    
    public float getAlpha() {
        return alpha;
    }

    public void setAlpha(float alpha) {
        this.alpha = alpha;
        repaint();
    }

    @Override
    public Color getForeground() {
        return lColor;
    }

    @Override
    public void setForeground(Color color) {
        this.lColor = color;
        repaint();
    }

    @Override
    public Color getBackground() {
        return rColor;
    }

    @Override
    public void setBackground(Color color) {
        this.rColor = color;
        repaint();
    }

    public gradientBGAlpha() {
        initComponents();
    }

    public void changeColor(Color color) {
        lColor = color;
        repaint();
    }

    public void lightenDarken(int factor) {
        int red = rColor.getRed();
        int green = rColor.getGreen();
        int blue = rColor.getBlue();

        // Calculate the darkened RGB values by reducing each component proportionally
        red = Math.max(0, red + factor);
        green = Math.max(0, green + factor);
        blue = Math.max(0, blue + factor);

        rColor = new Color(red, green, blue);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setOpaque(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 703, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 388, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents
    Color lColor = Color.GRAY;
    Color rColor = new Color(255,255,255,200);

    @Override
    protected void paintComponent(Graphics g) {
        super.paintComponent(g);
        Graphics2D g2d = (Graphics2D) g;
        g2d.setRenderingHint(RenderingHints.KEY_RENDERING, RenderingHints.VALUE_RENDER_QUALITY);
        int w = getWidth(), h = getHeight();
        GradientPaint gp = new GradientPaint(0, 0, lColor, w, h, rColor);
        
        g2d.setPaint(gp);
        g2d.fillRect(0, 0, w, h);
        //g2d.drawImage(image, 0, 0, w, h, null);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
